### ISSUE TITLE
包的版本问题

### ISSUE THREAD

**Issue by RenYong1** [PANPEIWEN/ABC#6]
你好，我用的是windows系统。在复现代码过程中，运行到model/build_segmentor.py文件夹时，会报一个 
decode_class = globals()[decode_name]
KeyError: 'ABC'
的错误，怀疑是包（python）的版本问题,可否提供一下详细的环境相关包版本信息捏？

**Comment by PANPEIWEN** [comment]
> 你好，我用的是windows系统。在复现代码过程中，运行到model/build_segmentor.py文件夹时，会报一个 decode_class = globals()[decode_name] KeyError: 'ABC' 的错误，怀疑是包（python）的版本问题,可否提供一下详细的环境相关包版本信息捏？

你好 windows系统可能会有点问题 建议你换成linux系统 环境包这边 遇到缺少包的情况直接pip安装就可以 对版本没那么敏感 你可以把具体的报错信息发出来 我看一下

**Comment by RenYong1** [comment]
D:\anaconda\envs\ABC\lib\site-packages\torchvision\io\image.py:13: UserWarning: Failed to load image Python extension: 
  warn(f"Failed to load image Python extension: {e}")
Traceback (most recent call last):
  File "E:/paper/small_target_detection/ABCject/ABC-main/train.py", line 306, in <module>
    main(args)
  File "E:/paper/small_target_detection/ABCject/ABC-main/train.py", line 292, in main
    trainer = Train(args, cfg)
  File "E:/paper/small_target_detection/ABCject/ABC-main/train.py", line 85, in __init__
    self.model = build_model(self.cfg)
  File "E:\paper\small_target_detection\ABCject\ABC-main\build\build_model.py", line 11, in build_model
    model = Model(cfg)
  File "E:\paper\small_target_detection\ABCject\ABC-main\model\build_segmentor.py", line 18, in __init__
    decode_class = globals()[decode_name]
KeyError: 'ABC'
你好，就是这个问题，我就是怀疑是系统的问题，可能windows系统确实调不通这个带代码哦

**Comment by PANPEIWEN** [comment]
不好意思 我发现这是一个bug
你只需要将configs/_base_/model/abcnet.py文件下的decode_head中的type改为'ABCNet'即可

RenYong1 ***@***.***> 于2023年4月27日周四 10:19写道：
